//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceBroker.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analysis()
        {
            this.Answers = new HashSet<Answer>();
            this.AnswerGroups = new HashSet<AnswerGroup>();
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid AnalysisDefinitionId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<int> AnalysisStateId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AnalysisDefinition AnalysisDefinition { get; set; }
        public virtual AnalysisState AnalysisState { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerGroup> AnswerGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
