//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceBroker.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid Id { get; set; }
        public System.Guid AnalysisId { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> OptionGroupId { get; set; }
        public Nullable<int> OptionId { get; set; }
        public Nullable<System.Guid> AnswerGroupId { get; set; }
        public string AnswerText { get; set; }
        public bool IsValid { get; set; }
        public Nullable<bool> IsFinal { get; set; }
        public bool InHighlighted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Analysis Analysis { get; set; }
        public virtual Option Option { get; set; }
        public virtual Question Question { get; set; }
    }
}
