//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceBroker.DataRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.NextQuestions = new HashSet<NextQuestion>();
            this.NextQuestions1 = new HashSet<NextQuestion>();
        }
    
        public int Id { get; set; }
        public System.Guid SectionId { get; set; }
        public int QuestionTypeId { get; set; }
        public Nullable<int> OptionGroupId { get; set; }
        public string QuestionText { get; set; }
        public string Comments { get; set; }
        public string HelpText { get; set; }
        public string AnswerLabel { get; set; }
        public string AnswerValidationExpression { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NextQuestion> NextQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NextQuestion> NextQuestions1 { get; set; }
        public virtual OptionGroup OptionGroup { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Section Section { get; set; }
    }
}
